export const ROUTES = {
  home: "/",
  projects: "/projects",
  projectDetails: "/projects/:projectId",
  addProject: "/projects/new",
  editProject: "/projects/:projectId/edit",
  storyBoard: "/projects/:projectId/stories",
  storyDetails: "/projects/:projectId/stories/:storyId",
  addStory: "/projects/:projectId/stories/new",
  editStory: "/projects/:projectId/stories/:storyId/edit",
  taskDetails: "/projects/:projectId/tasks/:taskId",
  addTask: "/projects/:projectId/tasks/new",
  adminUsers: "/admin/users",
  login: "/login",
  accountStatus: "/account-status",
  notFound: "*",
} as const;
